
networks:
  my_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    image: backend
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: "host.docker.internal"  
      POSTGRES_PORT: "8005"           
      POSTGRES_USER: "postgres"          
      POSTGRES_PASSWORD: "utec"     
      POSTGRES_DATABASE: "MY_DB"  
    networks: 
      - my_network
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  frontend:
    build:
      context: .
      dockerfile: DockerFile
      args:
        NEXT_PUBLIC_BACK_API_URL: http://98.84.92.116:8000
    image: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACK_API_URL=http://98.84.92.116:8000
    restart: always
    depends_on:
      - backend
    networks: 
      - my_network
    expose:
      - "3000"
