# Usa una imagen base oficial de Python
FROM python:3.10-slim-buster

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requisitos e instala las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación al directorio de trabajo
COPY . .

# Expone el puerto en el que la aplicación FastAPI se ejecutará
EXPOSE 8000

# Comando para ejecutar la aplicación usando Uvicorn
# 'main:app' se refiere al archivo 'main.py' y al objeto 'app' de FastAPI dentro de él
# --host 0.0.0.0 permite que la aplicación sea accesible desde fuera del contenedor
# --port 8000 es el puerto interno en el que Uvicorn escuchará
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]